# Site settings
title: In Digits
email: shailesh@indigits.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, research, ideas, and ramblings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://shailesh1729.github.io" # the base hostname & protocol for your site
twitter_username: shailesh1729
github_username:  shailesh1729

# Build settings
encoding: utf-8
highlighter: pygments
markdown: kramdown
permalink: pretty
