baseURL: "https://indigits.com/"
languageCode: 'en-us'
title: 'In Digits'
theme: PaperMod
paginate: 5
DefaultContentLanguage: en
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-XJSRMENLM4
copyright: "@ 2020-Present Shailesh Kumar, Some rights reserved"
minify:
    disableXML: true
    # minifyOutput: true
rssLimit: 20
author:
  name: Shailesh Kumar
  email: shailesh@indigits.com

menu:
    main:
        - name: Research
          url: research
          weight: 1
        - name: Software
          url: software
          weight: 2
        - name: Posts
          url: post
          weight: 3
        - name: Archives
          url: archives/
          weight: 5
        - name: Search
          url: search/
          weight: 5
        - name: Links
          url: links
          weight: 8
        - name: About
          url: about
          weight: 9
        - name: Tags
          url: tags/
          weight: 10


markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    defaultTheme: auto

    socialIcons:
        - name: github
          url: "https://github.com/shailesh1729"
        - name: twitter
          url: "https://twitter.com/shailesh1729"
        - name: Rss
          url: "index.xml"

    editPost:
      URL: "https://github.com/shailesh1729/shailesh1729.github.io/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
