baseURL = "https://indigits.com/"
languageCode = "en-us"
title = "In Digits"
theme = "relearn"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
googleAnalytics = "G-XJSRMENLM4"
copyright = "@ 2020-Present Shailesh Kumar, Some rights reserved"
rssLimit = 20

[author]
name = "Shailesh Kumar"
email = "shailesh@indigits.com"

[pagination]
pagerSize = 5

[minify]
disableXML = true
# minifyOutput = true

[markup.tableOfContents]
endLevel = 3
ordered = true
startLevel = 2

# Enable output formats needed by the theme
[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]

# Configuration for the Relearn theme
[params]
themeVariant = ["auto", "sienna", "zen-light", "zen-dark"]
themeVariantAuto = ["zen-light", "zen-dark"]
 # Set the title of the sidebar menu
titleSeparator = "::"
disableLandingPageButton = false
# Disable inline copy to clipboard button in code blocks, if you want
disableInlineCopyToClipboard = true
# Disable the breadcrumb navigation, if you want
disableBreadcrumb = false
# Disable next/previous links, if you want
disableNextPrev = false
enableBlockCodeWrap = true
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
defaultTheme = "auto"
# Automatically expand the menu to the current page
alwaysopen = true
# Enable KaTeX for math formulas
math = true
# Disable search functionality, if you want
[search]
disable = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/shailesh1729"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/shailesh1729"
[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[params.editPost]
URL = "https://github.com/shailesh1729/shailesh1729.github.io/content"
Text = "Suggest Changes"
appendFilePath = true

[params.cover]
responsiveImages = false
linkFullImages = true

[privacy.vimeo]
disabled = false
simple = true
[privacy.x]
disabled = false
enableDNT = true
simple = true
[privacy.instagram]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
